services:
  - type: web
    name: judgeaccount
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn judge_review:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: judgeaccount-db
          property: connectionString

databases:
  - name: judgeaccount-db
    databaseName: judgeaccount
    user: judgeaccount